### ISSUE TITLE
if_file, mkdir are not working synchronously 

### ISSUE THREAD

**Issue by silveraven** [puritys/nodejs-phplike#4]
Idea of this package is great, but this issue hurts me badly. 
```
if (!mkdir(MODULES_DIR)) {
    console.log("Error: Path '" + MODULES_DIR + "' exists, but is not a directory.");
    exit();
}
```
The code above enters `if` section even though **I know** there's no file or directory (so it will create one). Directory is created right after app exits. Assigning `mkdir` to variable doesn't help.

**Comment by puritys** [comment]
Thank you for report this bug, I fixed it now.

Here is the code diff:
https://github.com/puritys/nodejs-phplike/commit/de3c0c6fcd5928ef78a24cc1d94bd114123f5ec7


New package: phplike@2.5.2
