### ISSUE TITLE
Async methods

### ISSUE THREAD

**Issue by simon-p-r** [puritys/nodejs-phplike#5]
Hi

Nice module, are you planning on adding any async methods as this is what node is best at?

Thanks
Simon

**Comment by puritys** [comment]
This project's purpose is for implementing PHP functions to Node.js, PHP is a synchronize programming language. So I will not add any asynchronize method in this project. The package node-cgi will help you on creating a PHP-like website for using nodejs-phplike.

Sync and Async method have different pros and cons. If you really want to use async method in   your whole Node.js product. There are million of Node.js packages you can use.
