### ISSUE TITLE
http_build_query does not encode square brackets

### ISSUE THREAD

**Issue by jhorbulyk** [puritys/nodejs-phplike#8]
Consider the following PHP code:

```php
$params = [
    'foo' => [
        [
            'bar' => 'baz',
            'operator' => '>'
        ]
    ]
];
print(http_build_query($params));
```

The output is:
``foo%5B0%5D%5Bbar%5D=baz&foo%5B0%5D%5Boperator%5D=%3E``
which decodes to 
``foo[0][bar]=baz&foo[0][operator]=>``

Consider the following JS code:
``` javascript
var http_build_query = require('phplike/module.js').http_build_query;
var params = {
    foo: [
        {bar:'baz', operator: '>'}    
    ]
};
console.log(http_build_query(params));
```

The result is 
``foo[0][bar]=baz&foo[0][operator]=%3E`` 
which matches neither the pre or post encoded values for the php function.

Is this a bug which should be fixed?

**Comment by puritys** [comment]
New version phplike@2.5.5
